package ShortestPath;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*<pre>
 * Class        ShowGraphs.java
 * Description  A class that shows the coresponding graphs with the text files.
 * Platform     jdk 1.8.0_291; NetBeans IDE 11.3; PC Windows 10
 * Course       CS 143
 * Hourse       4 hours and 17 minutes
 * Date         6/4/2021
 * History Log  
 * @author	<i>Leanne Vu</i>
 * @version 	%1% %2%
 * @see     	javax.swing.JDialog
 *</pre>
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class ShowGraphs extends javax.swing.JDialog
{
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Constructor  ShowGraphs()-default constructor
     * Description  Create an instance of the GUI form with predefined image.
     * Date         6/4/2021
     * History Log  7/18/2018, 5/7/2020
     * @author      <i>Leanne Vu</i>
     * @param       parent Frame
     * @param       modal boolean
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public ShowGraphs(java.awt.Frame parent, boolean modal)
    {
        //super(parent, modal);
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(
                "src/Images/Cities_small.png"));
        // center the application
        setLocationRelativeTo(null);
        setAlwaysOnTop(true);
        setModal(true);
    }
    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     *<pre>
     * Constructor  ShowGraphs()-default constructor
     * Description  Uses passed parameter to show the corresponding image 
     *              while creating an instance of the GUI/
     * Date         6/4/2021
     * History Log  7/18/2018, 5/7/2020
     * @author      <i>Leanne Vu</i>
     * @param       textName String
    *</pre>
    *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public ShowGraphs(String textName) {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(
                "src/Images/Cities_small.png"));
        setLocationRelativeTo(null);
        setAlwaysOnTop(true);
        setModal(true);
        this.setTitle("Graph of " + textName);
        setPicture(graphsJLabel, "src/Images/", textName);
    }
    
   /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    *	Method		setPicture()
    *	Description     Method made so creating images with multiple files would
    *                   be much more convenient.
    *   @param          label JLabel
    *   @param          folder String
    *   @param          name String
    *	@author         <i>Leanne Vu</i>
    *	Date            3/8/2021
    *   history log
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
    public void setPicture (JLabel label, String folder, String name) {
        String image = folder + name + ".png";
        //sets label to the corresponding player
        label.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphsJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Show File Content and Corresponding Graphs");

        graphsJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WeightedGraphSample0.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(graphsJLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(graphsJLabel)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel graphsJLabel;
    // End of variables declaration//GEN-END:variables
}
